<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behaviorTreeMetamodel" nsURI="http://www.example.org/behaviorTreeMetamodel"
    nsPrefix="behaviorTreeMetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Tree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtree" upperBound="-1"
        eType="#//Tree" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeChild" upperBound="-1"
        eType="#//CompositeNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionChild" upperBound="-1"
        eType="#//ActionNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionChild" upperBound="-1"
        eType="#//ActionNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionChild" upperBound="-1"
        eType="#//ConditionNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtree" upperBound="-1"
        eType="#//Tree" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeChild" upperBound="-1"
        eType="#//CompositeNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceNode" eSuperTypes="#//CompositeNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FallbackNode" eSuperTypes="#//CompositeNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tree" lowerBound="1" upperBound="-1"
        eType="#//Tree" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
